version: "3"
services:
  # webapp:
  #   build: .
  #   container_name: webapp
  #   ports:
  #     - "5000:5000"
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      # - "5432:5432"
      - ${PORT_LOCAL}:${PORT_DOCKER}
    environment:
      # - POSTGRES_DB=${POSTGRES_DB}
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:  # Persist the db data
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-data:
